services:
  playground:
    tty: true
    restart: always
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/workspace
      - playground_node_modules:/workspace/node_modules

volumes:
  playground_node_modules:
